# Generated by Django 3.0.5 on 2021-02-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacao',
            options={'ordering': ('-data_interacao',), 'verbose_name': 'Interação', 'verbose_name_plural': 'Interações'},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ('-ultima_atualizacao',), 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AlterField(
            model_name='interacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='tickets.Solicitacao'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='solicitacoes'),
        ),
    ]
